### PR TITLE
Fixes #6: ability to start/stop timer

### LINKED ISSUE #6: Support disable / unregister.
Currently the constructor adds a timer to the event loop, but no reference to this timer is saved.

I'd like to be able to either destroy the `PCNTL` object or unregister it from the event loop.

A simple solution would be to store the result of `$loop->addPeriodicTimer` and implement a stop / start mechanism:

```
public function stop() {
    if (isset($this->timer) && $this->timer->isActive()) {
        $this->timer->cancel();
    }
}

public function start() {
    if (!isset($this->timer) || !$this->timer->isActive()) {
        $this->timer = $this->loop->addPeriodicTimer($this, $this->interval);
    }
}
```

I can make a PR if you want.

### PR DESCRIPTION
**Pull request by nick4fake**

### CODE REVIEW

**Comment by mkraemer** [comment]
Cool stuff, thanks!

Tests fails on PHP5.4 because of the used class constant in L48 of PCNTLTest.php
Can you replace it with 'React\EventLoop\Timer\TimerInterface'?

I'll merge and release a new version :)

**Comment by nick4fake** [comment]
oh, sorry, my fault. Did not notice you are supporting PHP 5.4.

Will do that soon

**Comment by mkraemer** [comment]
Yeah, no worries :) As soon as there's a good reason for dropping support for 5.4 I'm good with that, but in this case it doesn't seem necessary.. thx

**Comment by mkraemer** [comment]
I've tagged release v2.2.0

Thanks! :)

**Pull request merged**
